### ISSUE TITLE
jekyll 3.8.4 | Error:  undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by christoph4711** [open-sdg/open-sdg-site-starter#39]
Hi there,
 something went wrong with bulding the page.

Configuration file: /home/circleci/repo/_config.yml
            Source: /home/circleci/repo
       Destination: /home/circleci/repo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Invalid theme folder: _sass
      Remote Theme: Using theme open-sdg/open-sdg
Invalid theme folder: _sass
jekyll 3.8.4 | Error:  undefined method `each' for nil:NilClass
Exited with code 1

Find my _config.yml here: https://github.com/christoph4711/open-sdg-site-starter/blob/develop/_config.yml

Any Ideas?

Sorry i'm such a greenhorn in this, starting yesterday ;-)

**Comment by brockfanning** [comment]
@christoph4711 Hey no problem - that message usually means that the data source is not available. So first I think we should figure out why your data repository is not deploying successfully.

**Comment by brockfanning** [comment]
@christoph4711 In the Quick Start [here](https://open-sdg.readthedocs.io/en/latest/quick-start/#add-projects-to-circlecicom), on step 3.6, can you confirm that you entered specifically "gh-staging" as the "Hostname" when you were adding the private SSH key in CircleCI?

**Comment by christoph4711** [comment]
I think tha's correct 

![image](https://user-images.githubusercontent.com/53389268/62821647-5bac5100-bb78-11e9-80e0-249a404f49c7.png)

**Comment by christoph4711** [comment]
Sorry wrong button, won't close thas issue.....

**Comment by brockfanning** [comment]
Hmm, things look pretty good now, but for some reason the data is not getting deployed to Github Pages. If you go [here](https://github.com/christoph4711/open-sdg-site-starter/settings) and scroll down to "Github Pages" what does it say under "Source"?

**Comment by christoph4711** [comment]
there is something wrong,

can I somehow invite you to my repository, maybe that's easier then sening links and screenshots ;-)

![image](https://user-images.githubusercontent.com/53389268/62823790-688b6d80-bb95-11e9-8cc0-7b4b64fb4879.png)

**Comment by brockfanning** [comment]
I think we're close - try changing the Github Pages "source" from master to gh-pages. I think that should trigger a deployment to Github Pages, but we'll see.

**Comment by christoph4711** [comment]
After reading the docs I had this idea also, but where i can do this change?
there are ony these options in the source dropdown...

![image](https://user-images.githubusercontent.com/53389268/62824154-5bbd4880-bb9a-11e9-8e57-c32155ec29d4.png)

**Comment by brockfanning** [comment]
That's odd - can you confirm that you're looking at the settings for your data repository, open-sdg-**data**-starter?

**Comment by brockfanning** [comment]
Sorry, just realized I posted the wrong link above. The settings page is [here](https://github.com/christoph4711/open-sdg-data-starter/settings).

**Comment by christoph4711** [comment]
in the data repository the gh-pages option is there....
I picked that, and start the building process again....

Now an other Error occured:

#!/bin/bash -eo pipefail
bundle exec jekyll build
Configuration file: /home/circleci/repo/_config.yml
            Source: /home/circleci/repo
       Destination: /home/circleci/repo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Invalid theme folder: _sass
      Remote Theme: Using theme open-sdg/open-sdg
Invalid theme folder: _sass
  Liquid Exception: undefined method `[]' for nil:NilClass in /_layouts/default.html
jekyll 3.8.4 | Error:  undefined method `[]' for nil:NilClass
Exited with code 1

![image](https://user-images.githubusercontent.com/53389268/62824501-50b8e700-bb9f-11e9-84e9-0f9b9ad6203d.png)

**Comment by brockfanning** [comment]
I think the problem is that you're pointing to translation data that is getting a 404, [here](https://github.com/christoph4711/open-sdg-site-starter/blob/develop/_config.yml#L36). Maybe try pointing to a recent release of sdg-translations data instead: https://open-sdg.github.io/sdg-translations/translations-0.6.0.json

**Comment by christoph4711** [comment]
hm..... the same result.....

#!/bin/bash -eo pipefail
bundle exec jekyll build
Configuration file: /home/circleci/repo/_config.yml
            Source: /home/circleci/repo
       Destination: /home/circleci/repo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Invalid theme folder: _sass
      Remote Theme: Using theme open-sdg/open-sdg
Invalid theme folder: _sass
  Liquid Exception: undefined method `[]' for nil:NilClass in /_layouts/default.html
jekyll 3.8.4 | Error:  undefined method `[]' for nil:NilClass
Exited with code 1

**Comment by brockfanning** [comment]
I'm seeing an extra space in front of "http", try removing that space?

**Comment by christoph4711** [comment]
No errors any more! 👍  , but 404 Error on https://christoph4711.github.io/open-sdg-site-starter/

**Comment by christoph4711** [comment]
It works! 
i had to chose the gh-pages option on the site repository too!
Thank you so much!

**Comment by brockfanning** [comment]
No problem - also if you're wondering why the goal images aren't working: the "goal_image_base" in the _config.yml file needs to be just: "https://open-sdg.github.io/sdg-translations/assets/img/goals"

(remove the "/fr/6.png")
That help text is admittedly confusing there.

**Comment by christoph4711** [comment]
Last question (probably ;-) 
I’m  thinking about to develop such a reporting system for migration issues in Lower Saxony, based on the SDG repositories. It will be much smaller than SDG only 50 Indicators in three or four areas. (Population, education, labor market and social aspects of migration)
Each indicator should be available on different regional structures (eg. Lower Syxony on the whole, large and small cities etc..), the data should be displayed in some graphics and maps, and also should be available as csv….
What do you think, is this possible with the SDG repositories or do you have other repositories in mind that suit better to my ideas of an migration reporting system than the SDG repositories?

**Comment by brockfanning** [comment]
@christoph4711 That's a great question, and I think relevant to a lot of states/cities that might be interested in using Open SDG like this. Could I ask you to re-post your question over [here](https://github.com/open-sdg/open-sdg/issues)? That would make the discussion more visible to the rest of the Open SDG community.

**Comment by christoph4711** [comment]
Of course you can repost it. Do you mention me in the thread so that i'll bei part of the upcoming discussion...
