### ISSUE TITLE
Update FAQ content

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg-site-starter#51]
The language on the FAQ still has references to reporting status colors that aren't used in core Open SDG. https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_pages/faq.md

EDIT (Lucy):

- [x] Update reporting status question with all colours ('Reported online' changed to 'Reported' and add 'Not applicable')
- [x] Reorder questions so order matched UK (suggested by UR as order that makes sense)
- [x] Add table of contents
- [x] Add question about tiers - copy from UK but add note about Tier 3 indicators being removed as part of comp review
- [x] Make existing questions more general
- [x] Are there still issues with IE8? if so, are we working to fix them? (see What browsers can I use to view this website?)

**Comment by LucyGwilliamAdmin** [comment]
Fixed by #74
