### ISSUE TITLE
Unable to read data from: https://WohnungNDS.github.io/open-sdg-data-starter/de/meta/all.json

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg-site-starter#53]
Today I started another try with the open-sdg-site/ -data-sarter.
Following the instructions [here](https://open-sdg.readthedocs.io/en/latest/quick-start/#update-the-site-repository-configuration): 
the following error comes up:

Unable to read data from: https://WohnungNDS.github.io/open-sdg-data-starter/de/meta/all.json
404 Not Found
##[error]Process completed with exit code 1.

I can't fide the mentioned file in my repostiroy.... Any ideas?

Find my config.yml [here](https://github.com/WohnungNDS/open-sdg-site-starter/blob/develop/_config.yml)

**Comment by brockfanning** [comment]
@WohnungNDS It looks like something is going wrong during the deploy of the data repository. The error message seems to have something to do with access, as seen [here](https://github.com/WohnungNDS/open-sdg-data-starter/runs/835007578?check_suite_focus=true#step:6:35).

Do you know for sure if you completed [this step](https://open-sdg.readthedocs.io/en/latest/quick-start/#creating-an-access-token) for both the site and data repositories?

**Comment by WohnungNDS** [comment]
@brockfanning thank you.... I used one an the same access token for both, the site an the Data repository....

**Comment by brockfanning** [comment]
@WohnungNDS I believe you resolved this, so I'll go ahead and close. Feel free to re-open if needed.
