### ISSUE TITLE
Update the starting pages

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg-site-starter#65]
We should take a look at the [pages we're starting with](https://github.com/open-sdg/open-sdg-site-starter/tree/develop/_pages), and consider if any of them might be deleted. For example, do we need the "Contact" page?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning we have actually started using the contact us page in UK now: https://sdgdata.gov.uk/contact-us/

maybe could incorporate some of the changes there and then link to it from footer?

@AnnCorp what are your thoughts?

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin lets discuss at meeting this morning.

**Comment by LucyGwilliamAdmin** [comment]
Fixed by #74, #76, #77 and #79
