### ISSUE TITLE
a lot of erros to upload config

### ISSUE THREAD

**Issue by vmartin8888** [open-sdg/open-sdg-site-starter#91]
in test step, bring a lot of errors

- ./_test/site/config/index.html
  *  mailto:%email_address contains an invalid email address (line 164)
     <a href="mailto:%email_address">feedback</a>
- ./_test/site/contact-us/index.html
  *  mailto:%email_address contains an invalid email address (line 164)
     <a href="mailto:%email_address">feedback</a>
- ./_test/site/faq/index.html
  *  mailto:%email_address contains an invalid email address (line 164)
     <a href="mailto:%email_address">feedback</a>
- ./_test/site/goals/index.html
  *  mailto:%email_address contains an invalid email address (line 164)
     <a href="mailto:%email_address">feedback</a>
- ./_test/site/index.html
  *  mailto:%email_address contains an invalid email address (line 164)
     <a href="mailto:%email_address">feedback</a>
- ./_test/site/news/index.html
  *  mailto:%email_address contains an invalid email address (line 164)
     <a href="mailto:%email_address">feedback</a>
- ./_test/site/reporting-status/index.html
  *  mailto:%email_address contains an invalid email address (line 164)

**Comment by otis-bath** [comment]
@vmartin8888 can you remember what the fix was for this?
